version: 2
build:
  os: ubuntu-22.04
  tools:
    nodejs: '18'
    python: '3.13'
  apt_packages:
  - freeglut3-dev
  - xvfb
  - x11-utils
  jobs:
    post_system_dependencies:
    - nohup Xvfb $DISPLAY -screen 0 1400x900x24 -dpi 96 +extension RANDR +render &
    pre_install:
    - npm install -g yarn
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
python:
  install:
  - method: pip
    path: .
    extra_requirements:
      - docs
